name: Generate

on:
  workflow_dispatch: {} # Allows manual triggering of the workflow to generate SDK
  schedule:
    - cron: 0 0 * * * # Runs every day at midnight

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v7
    with:
      speakeasy_version: latest
      openapi_doc_location: https://stoplight.io/api/v1/projects/chord/chord-oms/nodes/swagger/v1/oms.yml?fromExportButton=true&snapshotType=http_service&deref=optimizedBundle&_ga=2.133572105.642002244.1674770724-1534481862.1665576582
      languages: |-
        - go
      mode: pr
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
